### ISSUE TITLE
assoc array bug

### ISSUE THREAD

**Issue by cidious** [leeoniya/dump_r.php#45]
Hello,
this kind of array
```php
$obj = [
  [
    'id' => 1,
    'unit' => 11,
    'action' => 21,
  ],
  [
    'id' => 2,
    'unit' => 12,
    'action' => 22,
  ],
  [
    'id' => 4,
    'unit' => 14,
    'comment' => 'xxx',
    'action' => 24,
  ],
];
```
renders in HTML as
![2015-07-14 12-57-48 test2 local dump_r test index php - google chrome](https://cloud.githubusercontent.com/assets/631488/8667972/046b62cc-2a28-11e5-8431-cace44ffd804.png)

**Comment by leeoniya** [comment]
the recordset detection code [1] is simple and analyzes at only the first 2 array elements to determine if all elements are uniform and simple. this is done for speed because it is impractical to analyze every element of the entire array for uniformity and other conditions. you will also run into similar issues if you have something where the first 2 elements are simple but other elements are complex:

```php
$obj = [
  [
    'id' => 1,
    'unit' => 11,
    'action' => 21,
  ],
  [
    'id' => 2,
    'unit' => 12,
    'action' => 22,
  ],
  [
    'id' => 4,
    'unit' => 14,
    'action' => ['a','b','c'],
  ],
];
```

I would suggest disabling recordset rendering and just dump this array normally since it is not uniform:

```php
dump_r\Rend::$recset_tbls   = false;     // recordset detection & table-style output
```
[1] https://github.com/leeoniya/dump_r.php/blob/master/src/dump_r/Node.php#L106

**Comment by cidious** [comment]
thank you
