### ISSUE TITLE
Please tag stable versions

### ISSUE THREAD

**Issue by xrstf** [leeoniya/dump_r.php#46]
I'm using your project in one of mine and the integration tests just failed because dump-r switched to PHP 5.4 and we're still stuck with PHP 5.3.

I would not have a problem with that, as I can simply require an older version of your library (``dev-master#5c8602e``). The problem is that Composer seems to clone the master branch first and check its composer.json, telling me that I need PHP 5.4.

I would highly appreciate tagged versions, including one tagged version for PHP 5.3.x.

**Comment by leeoniya** [comment]
Yikes, 5.3 is a relic, as is the `dump_r` revision that supported it.

I tried to do some trivial back-compat conversions on the current codebase to make an updated 5.3-compat branch, but hit an impasse since the current code now relies on traits and there's no trivial way to alter this.

If you give me the last commit that works for you on 5.3, I can tag it `1.1` and tag the commit after it as `2.0`.

**Comment by xrstf** [comment]
It was the one mentioned in the comment above, 5c8602e.

**Comment by leeoniya** [comment]
k, just making sure. tags are up.

**Comment by xrstf** [comment]
Thanks a bunch =)

**Comment by leeoniya** [comment]
:+1:
